[pytest]

addopts =
    -v
    --alluredir=reports
    --reruns 2
    --reruns-delay 2

python_files = test_*.py

testpaths = tests

markers =
   ui: UI automation tests
    api: API automation tests
    mcp: MCP AI-assisted tests
    